name: CI/CD QA Portfolio

on:
  push:
    paths:
      - 'Projects/saucedemo-pom-architecture/**'
      - 'Projects/serverest-ecommerce-api-e2e-automation/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'Projects/saucedemo-pom-architecture/**'
      - 'Projects/serverest-ecommerce-api-e2e-automation/**'
      - '.github/workflows/ci.yml'

jobs:
  # 🌐 Bloco de Automação UI com Cypress (SauceDemo)
  e2e-saucedemo-cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Executar Cypress Headless
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./Projects/saucedemo-pom-architecture
          command: npx cypress run