name: CI/CD Portfolio

on: [push, pull_request]

jobs:
  # Calculator Unit
  test-calculator-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7 

      - name: Set up JDK
        uses: actions/setup-java@v4.2.1 
        with:
          java-version: '26.0.1'
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: ./Projects/calculator-unit-ci
        run: mvn -B test
  
  # Sauce Demo
  e2e-saucedemo-cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./Projects/saucedemo-pom-architecture
          command: npx cypress run